# Generated by Django 5.1.5 on 2025-04-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
