# Generated by Django 5.1.5 on 2025-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voter_analytics', '0002_delete_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address_street_number', models.TextField()),
                ('address_street_name', models.TextField()),
                ('address_apartment_number', models.TextField()),
                ('address_zip_code', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_registration', models.DateField()),
                ('party_affiliation', models.CharField(blank=True, max_length=2, null=True)),
                ('precinct_number', models.TextField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
